# Generated by Django 2.0 on 2018-01-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180113_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
    ]
