# Generated by Django 2.0 on 2018-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180113_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
