# Generated by Django 2.0 on 2018-01-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180113_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shortcode',
        ),
    ]
