# Generated by Django 2.0 on 2018-01-13 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_userprofile_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shortcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
